/*TABLE OF PEOPLE*/
CREATE TABLE USERS(
  COD_USER      BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'THE PRIMARY KEY OF THE USER'
  ,COD_PEOPLE   BIGINT                          COMMENT 'COD OF THE PERSON'
  ,COD_TIPUSERS BIGINT                         COMMENT 'COD OF TYPE OF USERS'
  ,NAME         VARCHAR(120) NOT NULL           COMMENT 'THE NAME OF THE USER'
  ,CLAVE        VARCHAR(2000) NOT NULL          COMMENT 'THE PASSWORD OF THE USER'
  ,API_TOKEN    VARCHAR(6) NOT NULL             COMMENT 'TOKEN DE ACCESO'  
  ,IND_USR      ENUM('1','0')  NOT NULL         COMMENT 'IND OF THE USER TO ACCESS THE SYSTEM, 0=INACTIVE 1=ACTIVE'
  ,IND_INS      ENUM('1','0') NOT NULL          COMMENT 'IND OF THE FIRST TIME IN THE SYSTEM.'
  ,USR_ADD      VARCHAR(30) NOT NULL           COMMENT 'USER THAT ADDED THIS ROW'
  ,USR_UPD     VARCHAR(30) NOT NULL                COMMENT 'USER WHO MODIFIED THIS ROW'
  ,DAT_UPD     DATETIME NOT NULL                    COMMENT 'DATE THIS ROW WAS MODIFIED'
  ,DAT_ADD      DATETIME NOT NULL               COMMENT 'DATE THAT THIS ROW WERE ADDED'
  ,FOREIGN KEY `FK_PEOADD_PEOUSR`(`COD_PEOPLE`) REFERENCES `PA_PEOPLE`(`COD_PEOPLE`) ON DELETE CASCADE
  ,FOREIGN KEY `FK_TIPUSE_USERS` (`COD_TIPUSERS`) REFERENCES `PA_TIPUSERS`(`COD_TIPUSERS`) ON DELETE CASCADE
)ENGINE=INNODB 
CHARACTER SET UTF8 
COLLATE UTF8_UNICODE_CI;


CREATE TABLE PA_TIPUSERS(
   COD_TIPUSERS   BIGINT PRIMARY KEY AUTO_INCREMENT  COMMENT 'THE PRIMARY KEY OF TYPE OF USER'
  ,/**/COD_USER       BIGINT                         COMMENT 'COD OF USER'
  ,NOM_TYPE       VARCHAR(120) NOT NULL UNIQUE       COMMENT 'THE NAME OF THE TYPE OF USER'
  ,DES_TYPE       VARCHAR(2000) NOT NULL             COMMENT 'DESCRIPTION OF THE TYPE OF USER'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


/*TABLE OF GENERAL INFORMATION OF PEOPLE*/
CREATE TABLE PA_PEOPLE(
  COD_PEOPLE   BIGINT PRIMARY KEY AUTO_INCREMENT    COMMENT 'COD OF THE PERSON'
  ,ID          VARCHAR(60) NOT NULL                COMMENT 'THE ID OF THE PERSON, IT COULD THE PASSPORT OR NATIONAL ID'
  ,TIP_DOCUMENT ENUM("ID","PASSPORT","LICENSE") NOT NULL COMMENT"THE TYPE OF DOCUMENTATION OF THE PERSON",
  ,FIRSTNAME   VARCHAR(120) NOT NULL                COMMENT 'THE FIRTS NAME OF A PERSON'
  ,MIDDLENAME  VARCHAR(120) NOT NULL                COMMENT 'THE MIDDLE NAME OF A PERSON'
  ,LASTNAME    VARCHAR(120) NOT NULL                COMMENT 'THE LAST NAME OF A PERSON'
  ,SEX         ENUM('M','W','F','D') NOT NULL       COMMENT 'THE SEX OF A PERSON'
  ,IND_CIVIL   ENUM('S','M','W') NOT NULL           COMMENT 'THE CIVILIAN STATUS OF A PERSON'
  ,AGE         TINYINT NOT NULL                     COMMENT 'THE AGE OF A PERSON'
  ,TIP_PERSON  ENUM('N','J') NOT NULL               COMMENT 'NATURAL OR JURIDICAL'
  ,USR_ADD     VARCHAR(30) NOT NULL                COMMENT 'USER THAT ADDED THIS ROW'
  ,USR_UPD     VARCHAR(30) NOT NULL                COMMENT 'USER WHO MODIFIED THIS ROW'
  ,DAT_ADD     DATETIME NOT NULL                    COMMENT 'DATE THAT THIS ROW WERE ADDED'
  ,DAT_UPD     DATETIME NOT NULL                    COMMENT 'DATE THIS ROW WAS MODIFIED'

)ENGINE=INNODB 
CHARACTER SET UTF8 
COLLATE UTF8_UNICODE_CI;













/* *BRANCH OFFICE* */

/*TABLE TYPE OF PARCEL*/
CREATE TABLE BO_PARCEL (
COD_PARCE BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT"COD OF PARCEL",

)ENGINE=INNODB 
CHARACTER SET UTF8 
COLLATE UTF8_UNICODE_CI;

/*TABLE TYPE OF PARCEL*/
 CREATE TABLE BO_LOCKER(
 )ENGINE=INNODB 
CHARACTER SET UTF8 
COLLATE UTF8_UNICODE_CI;


 
 /*TABLE TYPE OF TROLLEY*/
 CREATE TABLE BO_TROLLEY(
 
 )ENGINE=INNODB 
CHARACTER SET UTF8 
COLLATE UTF8_UNICODE_CI;
 
 
 CREATE TABLE PAYMENT(
 
 )ENGINE=INNODB 
CHARACTER SET UTF8 
COLLATE UTF8_UNICODE_CI;
 
 